#include <OpenKNXHardware.h>

#ifdef BOARD_ABTOOLS_FINGERPRINT_V13
    #define SCANNER_RX_PIN 5
    #define SCANNER_TX_PIN 4    
    #define INFO_LED_PIN 11
    #define INFO_LED_PIN_ACTIVE_ON HIGH
    #define PROG_LED_PIN 10
    #define PROG_LED_PIN_ACTIVE_ON HIGH
    #define PROG_BUTTON_PIN 9
    #define PROG_BUTTON_PIN_INTERRUPT_ON FALLING

    #define KNX_UART_TX_PIN 12
    #define KNX_UART_RX_PIN 13
    #define SAVE_INTERRUPT_PIN 0

    #define SCANNER_TOUCH_PIN 2
    #define TOUCH_LEFT_PIN 26
    #define TOUCH_RIGHT_PIN 27
    #define LED_GREEN_PIN 24
    #define LED_RED_PIN 25

    #define OPENKNX_SWA_CHANNEL_COUNT 1
    #define OPENKNX_SWA_SET_PINS 14
    #define OPENKNX_SWA_RESET_PINS 15
    #define OPENKNX_SWA_SET_ACTIVE_ON LOW
    #define OPENKNX_SWA_RESET_ACTIVE_ON LOW
    #define OPENKNX_SWA_BISTABLE_IMPULSE_LENGTH 50

    #define OPENKNX_BI_GPIO_PINS 28, 18, 29, 19
    #define OPENKNX_BI_GPIO_COUNT 4
#endif


#ifdef OKNXHW_REG1_BASE_V1
    #define SCANNER_RX_PIN 5
    #define SCANNER_TX_PIN 4    
    #define SCANNER_TOUCH_PIN 2
    #define TOUCH_LEFT_PIN 26
    #define TOUCH_RIGHT_PIN 27
    #define LED_GREEN_PIN 24
    #define LED_RED_PIN 25

    #define OPENKNX_SWA_CHANNEL_COUNT 1
    #define OPENKNX_SWA_SET_PINS 14
    #define OPENKNX_SWA_RESET_PINS 15
    #define OPENKNX_SWA_SET_ACTIVE_ON LOW
    #define OPENKNX_SWA_RESET_ACTIVE_ON LOW
    #define OPENKNX_SWA_BISTABLE_IMPULSE_LENGTH 50

    #define OPENKNX_BI_GPIO_PINS 28, 18, 29, 19
    #define OPENKNX_BI_GPIO_COUNT 4
#endif


#ifdef OKNXHW_UP1_CONTROLLER2040
// UP1 Pins
// E_SCL 21  RX
// E_SDA 20  TX
// F_SCL 19  Touch
// F_SDA 18

    #define SCANNER_RX_PIN 5 // fingerprint.cpp L23
    #define SCANNER_TX_PIN 4 // fingerprint.cpp L23   
    #define SCANNER_TOUCH_PIN 2
    #define TOUCH_LEFT_PIN 26
    #define TOUCH_RIGHT_PIN 27
    #define LED_GREEN_PIN 24
    #define LED_RED_PIN 25

    #define OPENKNX_SWA_CHANNEL_COUNT 1
    #define OPENKNX_SWA_SET_PINS 14
    #define OPENKNX_SWA_RESET_PINS 15
    #define OPENKNX_SWA_SET_ACTIVE_ON LOW
    #define OPENKNX_SWA_RESET_ACTIVE_ON LOW
    #define OPENKNX_SWA_BISTABLE_IMPULSE_LENGTH 50

    #define OPENKNX_BI_GPIO_PINS 28, 18, 29, 19
    #define OPENKNX_BI_GPIO_COUNT 4
#endif