#pragma once

#define MAIN_Version "b26e4c3"
#define KNX_Version "2.2.1+1b646c1"
#define MODULE_AccessControl_Version "0.10.1+8714e13"
#define MODULE_AccessControl_Version_Major 0
#define MODULE_AccessControl_Version_Minor 10
#define MODULE_AccessControl_Version_Revision 1
#define MODULE_AccessControl_ETS 10
#define MODULE_Common_Version "1.5.0+8937d53"
#define MODULE_Common_Version_Major 1
#define MODULE_Common_Version_Minor 5
#define MODULE_Common_Version_Revision 0
#define MODULE_Common_ETS 21
#define MODULE_HardwareConfig_Version "1.0.0+d4f8a07"
#define MODULE_HardwareConfig_Version_Major 1
#define MODULE_HardwareConfig_Version_Minor 0
#define MODULE_HardwareConfig_Version_Revision 0
#define MODULE_HardwareConfig_ETS 16
#define MODULE_LogicModule_Version "3.7.2+5e30d8d"
#define MODULE_LogicModule_Version_Major 3
#define MODULE_LogicModule_Version_Minor 7
#define MODULE_LogicModule_Version_Revision 2
#define MODULE_LogicModule_ETS 55
#define MODULE_SwitchActuator_Version "0.1.0+5e6b79b"
#define MODULE_SwitchActuator_Version_Major 0
#define MODULE_SwitchActuator_Version_Minor 1
#define MODULE_SwitchActuator_Version_Revision 0
#define MODULE_SwitchActuator_ETS 1
#define MODULE_BinaryInput_Version "0.2.1+7b628ef"
#define MODULE_BinaryInput_Version_Major 0
#define MODULE_BinaryInput_Version_Minor 2
#define MODULE_BinaryInput_Version_Revision 1
#define MODULE_BinaryInput_ETS 2
#define MODULE_VirtualButton_Version "0.5.2+06ebdcb"
#define MODULE_VirtualButton_Version_Major 0
#define MODULE_VirtualButton_Version_Minor 5
#define MODULE_VirtualButton_Version_Revision 2
#define MODULE_VirtualButton_ETS 5
#define MODULE_FileTransferModule_Version "0.1.2+4be8e34"
#define MODULE_FileTransferModule_Version_Major 0
#define MODULE_FileTransferModule_Version_Minor 1
#define MODULE_FileTransferModule_Version_Revision 2
#define MODULE_FileTransferModule_ETS 1
