#pragma once

#define MAIN_Version "a6d0975"
#define KNX_Version "2.1.2+764900e"
#define MODULE_AccessControl_Version "0.9.0+0b85b71"
#define MODULE_AccessControl_Version_Major 0
#define MODULE_AccessControl_Version_Minor 9
#define MODULE_AccessControl_Version_Revision 0
#define MODULE_AccessControl_ETS 9
#define MODULE_Common_Version "1.3.0+8b5f341"
#define MODULE_Common_Version_Major 1
#define MODULE_Common_Version_Minor 3
#define MODULE_Common_Version_Revision 0
#define MODULE_Common_ETS 19
#define MODULE_HardwareConfig_Version "1.0.0+31b5142"
#define MODULE_HardwareConfig_Version_Major 1
#define MODULE_HardwareConfig_Version_Minor 0
#define MODULE_HardwareConfig_Version_Revision 0
#define MODULE_HardwareConfig_ETS 16
#define MODULE_LogicModule_Version "3.5.2+9a1cfe1"
#define MODULE_LogicModule_Version_Major 3
#define MODULE_LogicModule_Version_Minor 5
#define MODULE_LogicModule_Version_Revision 2
#define MODULE_LogicModule_ETS 53
#define MODULE_GPIOModule_Version "0.0.0+b95bb8c"
#define MODULE_GPIOModule_Version_Major 0
#define MODULE_GPIOModule_Version_Minor 0
#define MODULE_GPIOModule_Version_Revision 0
#define MODULE_GPIOModule_ETS 0
#define MODULE_SwitchActuator_Version "0.1.0+bc82298"
#define MODULE_SwitchActuator_Version_Major 0
#define MODULE_SwitchActuator_Version_Minor 1
#define MODULE_SwitchActuator_Version_Revision 0
#define MODULE_SwitchActuator_ETS 1
#define MODULE_BinaryInput_Version "0.2.0+9fd5ad1"
#define MODULE_BinaryInput_Version_Major 0
#define MODULE_BinaryInput_Version_Minor 2
#define MODULE_BinaryInput_Version_Revision 0
#define MODULE_BinaryInput_ETS 2
#define MODULE_VirtualButton_Version "0.5.0+e39365e"
#define MODULE_VirtualButton_Version_Major 0
#define MODULE_VirtualButton_Version_Minor 5
#define MODULE_VirtualButton_Version_Revision 0
#define MODULE_VirtualButton_ETS 5
#define MODULE_FileTransferModule_Version "0.1.0+2669301"
#define MODULE_FileTransferModule_Version_Major 0
#define MODULE_FileTransferModule_Version_Minor 1
#define MODULE_FileTransferModule_Version_Revision 0
#define MODULE_FileTransferModule_ETS 1
